version: '3.8'
services:
  frontend:
    image: akash879/techdome-frontend:v1
    ports:
      - "3001:3001"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: akash879/techdome-backend:v1
    ports:
      - "5000:5000"
    environment:
      - DB=mongodb://admin:password@mongo:27017/techdome
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_ROOT_DB=techdome
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge